# Generated by Django 6.0.5 on 2026-05-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorylog',
            new_name='inventory_i_store_i_ae8fce_idx',
            old_name='inventory_i_store_i_1ed536_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorylog',
            new_name='inventory_i_product_fb4c37_idx',
            old_name='inventory_i_product_5e7366_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorylog',
            new_name='inventory_i_action_aa3d69_idx',
            old_name='inventory_i_action_364f2f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_store_i_02dc95_idx',
            old_name='inventory_p_store_i_9130fb_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_store_i_f73da2_idx',
            old_name='inventory_p_store_i_3301df_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_store_i_141273_idx',
            old_name='inventory_p_store_i_679f29_idx',
        ),
    ]
