# Generated by Django 6.0.5 on 2026-05-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsreport',
            new_name='reports_ana_store_i_d555e5_idx',
            old_name='reports_ana_store_i_61f6de_idx',
        ),
    ]
