# Generated by Django 6.0.5 on 2026-05-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_store_i_32ec12_idx',
            old_name='sales_sale_store_i_eb166f_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_store_i_b61d1b_idx',
            old_name='sales_sale_store_i_79faf6_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_store_i_655baa_idx',
            old_name='sales_sale_store_i_c25f78_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sales_salei_product_f87493_idx',
            old_name='sales_sale_product_e8066a_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sales_salei_sale_id_413ea3_idx',
            old_name='sales_sale_sale_id_28710d_idx',
        ),
    ]
